#!/bin/sh
#
#     tiger - A UN*X security checking system
#     Copyright (C) 1993 Douglas Lee Schales, David K. Hess, David R. Safford
#
#     Please see the file `COPYING' for the complete copyright notice.
#
# default/gen_alias_sets - 06/14/93
#
#-----------------------------------------------------------------------------
#

[ -r /etc/aliases ] && {
  $GREP -v '^#' /etc/aliases |
  $SORT > $WORKDIR/etc_aliases.$$
  echo "/etc/aliases" > $WORKDIR/etc_aliases.$$.src
  echo $WORKDIR/etc_aliases.$$
}

[ -r /etc/mail/aliases ] && {
  $GREP -v '^#' /etc/mail/aliases |
  $SORT > $WORKDIR/etc_aliases.$$
  echo "/etc/mail/aliases" > $WORKDIR/etc_aliases.$$.src
  echo $WORKDIR/etc_aliases.$$
}

[ -r /etc/sendmail/aliases ] && {
  $GREP -v '^#' /etc/sendmail/aliases |
  $SORT > $WORKDIR/etc_aliases.$$
  echo "/etc/sendmail/aliases" > $WORKDIR/etc_aliases.$$.src
  echo $WORKDIR/etc_aliases.$$
}

[ -r /usr/lib/aliases ] && {
  $GREP -v '^#' /usr/lib/aliases |
  $SORT > $WORKDIR/etc_aliases.$$
  echo "/usr/lib/aliases" > $WORKDIR/etc_aliases.$$.src
  echo $WORKDIR/etc_aliases.$$
}

[ -n "$YP" ] && {
  $YPCAT -k aliases |
  $SED -e 's/ /:/' | 
  $SORT |
  $COMM -23 - $WORKDIR/etc_aliases.$$ > $WORKDIR/nis_aliases.$$
  echo "NIS" > $WORKDIR/nis_aliases.$$.src
  echo $WORKDIR/nis_aliases.$$
}
