#!/bin/sh
#
#     tiger - A UN*X security checking system
#     Copyright (C) 1993 Douglas Lee Schales, David K. Hess, David R. Safford
#
#     Please see the file `COPYING' for the complete copyright notice.
#
# default/gen_group_sets - 06/14/93
#
#-----------------------------------------------------------------------------
#

$GREP -v '^[-+]' /etc/group |
$SORT > $WORKDIR/etc_group.$$
echo "/etc/group" > $WORKDIR/etc_group.$$.src
echo $WORKDIR/etc_group.$$

[ -n "$YP" ] && {
  $YPCAT group |
  $SORT |
  $COMM -23 - $WORKDIR/etc_group.$$ > $WORKDIR/nis_group.$$
  echo "NIS" > $WORKDIR/nis_group.$$.src
  echo $WORKDIR/nis_group.$$
}

