#!/bin/sh
#
#     tiger - A UN*X security checking system
#     Copyright (C) 1993 Douglas Lee Schales, David K. Hess, David R. Safford
#
#     Please see the file `COPYING' for the complete copyright notice.
#
# getdisks - 06/24/93
#
#-----------------------------------------------------------------------------
#

$GET_MOUNTS local |
$AWK '{printf("%s ",$1)}
END {printf("\n")}' 
