#!/bin/sh
#
#     tiger - A UN*X security checking system
#     Copyright (C) 1993 Douglas Lee Schales, David K. Hess, David R. Safford
#
#     Please see the file `COPYING' for the complete copyright notice.
#
# sub/check_wdir - 06/14/93
#
#-----------------------------------------------------------------------------
# This script is not runnable directly.
# 
file="$1"

[ "$CONFIGURED_ALREADY" != "YES" ] && {
  echo "--ERROR-- [init008e] This script can not be run directly."
  exit 1
}

. $BASEDIR/initdefs

#
# If run in test mode (-t) this will verify that all required
# elements are set.
#
[ "$Tiger_TESTMODE" = 'Y' ] && {
  haveallcmds GREP CAT RM AWK GETCLIENTDIRS || exit 1
  haveallfiles WORKDIR || exit 1
  
  echo "--CONFIG-- [init003c] $0: Configuration ok..."
  exit 0
}

#------------------------------------------------------------------------
echo
echo "# Checking for writable directories..."

haveallcmds GREP CAT SED || exit 1
haveallvars WORKDIR || exit 1

[ ! -n "$FS_WDIRSYS" ] && FS_WDIRSYS="/tmp/ /usr/tmp/"

dltmpdirs=
[ -n "$HOSTNAMESLIST" ] &&
haveallcmds GETCLIENTDIRS AWK && {
  dltmpdirs=`$GETCLIENTDIRS |
             while read client rootdir
             do
               for dir in $FS_WDIRSYS
               do
                  echo "$rootdir$dir"
               done
             done
  `
}

set $FS_WDIRSYS $dltmpdirs

greps="$GREP -v '^'$1"

shift
for dir
do
  greps="$greps | $GREP -v '^'$dir"
done

$SED -e 's%\([^/]\)$%\1/%' $file |
eval $greps > $WORKDIR/wdir.tmp.$$

[ -s $WORKDIR/wdir.tmp.$$ ] && {
  echo "--INFO-- [fsys008i] The following directories are world writable:"
  $SORT $WORKDIR/wdir.tmp.$$
}

delete $WORKDIR/wdir.tmp.$$
