#!/bin/sh
#
#     tiger - A UN*X security checking system
#     Copyright (C) 1993 Douglas Lee Schales, David K. Hess, David R. Safford
#
#     Please see the file `COPYING' for the complete copyright notice.
#
# sub/check_nousrgrp - 06/14/93
#
#-----------------------------------------------------------------------------
# This script is not runnable directly.
# 

nouserfile="$1"
nogroupfile="$2"

[ "$CONFIGURED_ALREADY" != "YES" ] && {
  echo "--ERROR-- [init008e] This script can not be run directly."
  exit 1
}

. $BASEDIR/initdefs

#
# If run in test mode (-t) this will verify that all required
# elements are set.
#
[ "$Tiger_TESTMODE" = 'Y' ] && {
  haveallcmds GETCLIENTDIRS AWK GREP LS RM || exit 1
  haveallfiles WORKDIR || exit 1
  
  echo "--CONFIG-- [init003c] $0: Configuration ok..."
  exit 0
}

#------------------------------------------------------------------------

haveallcmds AWK GREP LS || exit 1
haveallvars WORKDIR || exit 1

[ -s "$nouserfile" ] && {
  echo '--WARN-- [xxxxx] The following files are unowned:'
  $SORT "$nouserfile"
  echo
}

[ -s "$nogroupfile" ] && {
  echo '--WARN-- [xxxxx] The following files have undefined groups ownership:'
  $SORT "$nogroupfile"
  echo
}
