#!/bin/sh
#
#     tiger - A UN*X security checking system
#     Copyright (C) 1993 Douglas Lee Schales, David K. Hess, David R. Safford
#
#     Please see the file `COPYING' for the complete copyright notice.
#
# HPUX/genpasswd - 06/14/93
#
#-----------------------------------------------------------------------------
#

local=0
for parm
do
  case "$parm" in
    -p) ;;
    -l) local=1;;
    *)	outfile="$parm";;
  esac
done


$GREP -v '^[-+]' /etc/passwd |
$SORT > $WORKDIR/etc_passwd.$$
echo "/etc/passwd" > $WORKDIR/etc_passwd.$$.src
echo $WORKDIR/etc_passwd.$$ >> $outfile

[ -n "$YP" ] && {
  $YPCAT passwd |
  $SORT |
  $COMM -23 - $WORKDIR/etc_passwd.$$ > $WORKDIR/nis_passwd.$$
  echo "NIS" > $WORKDIR/nis_passwd.$$.src
  echo $WORKDIR/nis_passwd.$$ >> $outfile
}
