#!/bin/sh
#
#     tiger - A UN*X security checking system
#     Copyright (C) 1993 Douglas Lee Schales, David K. Hess, David R. Safford
#
#     Please see the file `COPYING' for the complete copyright notice.
#
# util/logit - 04/22/93
#
#-----------------------------------------------------------------------------
# Lovely eh?

# Unduly complicated so that we can get rid of any nasty newlines
# (they are converted to ~'s).

{
  echo "$2" |
  $AWK '
    BEGIN {lc="";}
    {
      printf("%s%s", lc, $0);
      lc="~";
    }
  '
  echo
} >> $1
