#!/bin/sh
#
#     tiger - A UN*X security checking system
#     Copyright (C) 1993 Douglas Lee Schales, David K. Hess, David R. Safford
#
#     Please see the file `COPYING' for the complete copyright notice.
#
# IRIX/4/gen_inetd - 06/14/93
#
#-----------------------------------------------------------------------------
#

$GREP -v '^#' /usr/etc/inetd.conf |
$SORT > $WORKDIR/etc_inetd.$$
echo "/usr/etc/inetd.conf" > $WORKDIR/etc_inetd.$$.src
echo $WORKDIR/etc_inetd.$$
