#!/bin/sh
#
#     tiger - A UN*X security checking system
#     Copyright (C) 1993 Douglas Lee Schales, David K. Hess, David R. Safford
#
#     Please see the file `COPYING' for the complete copyright notice.
#
# SunOS/4/gen_alias_sets - 06/14/93
#
#-----------------------------------------------------------------------------
#
[ -f /usr/lib/aliases ] && {
  $GREP -v '^#' /usr/lib/aliases |
  $SORT > $WORKDIR/etc_aliases.$$
  echo "/usr/lib/aliases" > $WORKDIR/etc_aliases.$$.src
  echo $WORKDIR/etc_aliases.$$
}
